CREATE DATABASE `TESTDB`;#創建DATABASE
SHOW DATABASES;#顯示DATABASE
DROP DATABASE `TESTDB`;#刪除DATABASE
USE `TESTDB`;#使用DATABASE

SHOW TABLES;#顯示表格
DROP TABLE `NUMPLATE_DATA`;#刪除表格
DROP TABLE `PICTURE_DATA`;#刪除表格
DROP TABLE `NUMPIC_DATA`;#刪除表格
    
DESCRIBE `NUMPLATE_DATA`;#顯示表格擁有的的屬性列表
SELECT * FROM `NUMPLATE_DATA`;#列出表格所有資料
SELECT numplate FROM `NUMPLATE_DATA`;
UPDATE `NUMPLATE_DATA` SET out_time=null WHERE numplate='EQC-5371';

DESCRIBE `PICTURE_DATA`;#顯示表格擁有的的屬性列表
SELECT * FROM `PICTURE_DATA`;#列出表格所有資料
DELETE FROM `PICTURE_DATA` WHERE ID='10';
INSERT INTO `PICTURE_DATA`(picture) VALUES(LOAD_FILE('C:\MCUT_file\Independent Study\MySQL\Picture\Result.jpg'));

DESCRIBE `NUMPIC_DATA`;#顯示表格擁有的的屬性列表
SELECT * FROM `NUMPIC_DATA`;#列出表格所有資料
UPDATE `NUMPIC_DATA` SET picture=LOAD_FILE("C:/MCUT_file/Independent Study/MySQL/Picture/Result.jpg") WHERE numplate='EQC-5371';
